### ISSUE TITLE
Review retreat Eindhoven

### ISSUE THREAD

**Issue by jensroes** [jensroes/prowrite-mixture-models#11]
> We could have a writers' retreat in Eindhoven? Serious suggestion. Could just be two days. Jens and I put a lot of work into this when we were in Iowa, and it was really helpful actually both being in the same room, and free from other distractions. We have money to spend on this.

I think this is a good idea. I think we're looking into the weeks 9 - 13 September (there is an Away Day on the 12th, Mark) or Sept 17 to 20 (which is induction week but according to my diary at the moment I'm just teaching on the Monday of that week). I'm teaching quite a lot in term 1 so October might be difficult.

What do you think?

**Comment by Mark-Torrance** [comment]
It's going to have to be second week in October onwards for me if I want undistracted time. I'm away until 17th September then have massive student admin stuff (Projects) until end of first week of term. So from 30th September.

**Comment by RConijn** [comment]
Great idea!

Everything from Sept 9 - Nov 8 works for me (after November 8 I have to teach a lot), with a few exceptions:
- Preferably not on Monday Sept 9 (first day back from holiday, would be good to keep this day to catch up with emails/phd progress)
- I have Siebe-duty on Thursdays, but if I know the dates 4 weeks in advance I can adjust daycare accordingly.
- I have some teaching Sept 25, 27, Oct 4, Oct 25 (but might even be able to swap those dates if necessary)

All other days are fine.

**Comment by jensroes** [comment]
I don't think this is an option then unfortunately. October is teaching heavy for me and I won't be able to fit this in. If anything then Oct 22 to Oct 24 but including travelling.

So alternatively we can ask for an extension for the review and then meet in December. I was thinking about our PACE week as well but that's likely to be the week after Nov 8 which doesn't work for Rianne.

**Comment by Mark-Torrance** [comment]
I really want to make this work. Any chance of swapping some teaching? Or maybe Weds PM to returning Saturday early afternoon. Or even Thursday PM returning Saturday early afternoon - give then that 8 hours on the train is all good working time?

I could probably also do week beginning 23rd September if I get my act together.

**Comment by jensroes** [comment]
The first 3 weeks of term include a lot of teaching I can't swap and some stuff I need to prepare cause it's new to me. The earliest week I could make work with swaps is the week w/c Oct 21 (could leave to Eindhoven on Sat Oct 19 or Sun Oct 20 but have to leave before Friday Oct 25).

**Comment by RConijn** [comment]
Yes this works perfectly for me!

**Comment by jensroes** [comment]
I've got "domestic clearance" and I'll sort out teaching cover later. I'll also ask for an extension for the review just in case.

**Comment by Mark-Torrance** [comment]
Excellent. Rianne, which hotel should we stay in? We have a lot of money to spend :)

**Comment by Mark-Torrance** [comment]
I can book trains for us both. 

Out - Monday 21st Oct. Are you ok leaving St Pancras at 13:00 and arriving a bit after 19:00? There's a later train (15:00 to 21 something). 

Returning - Thursday 24th Oct. Do you want to leave at 8:44 (arriving 14:00) or 10:44 (arriving 16:00), or 12:44 (cheapest, though we don't care).

Really tempted to book first class. It's not much more. I bet there are rules saying we can't, though :)

**Comment by jensroes** [comment]
> Rianne, which hotel should we stay in? We have a lot of money to spend :)

Walking distance or bikes included and best breakfast in town please :) If possible with practice studio in the basement.

> Out - Monday 21st Oct. Are you ok leaving St Pancras at 13:00 and arriving a bit after 19:00? There's a later train (15:00 to 21 something).

The earlier train is better I think.

> Returning - Thursday 24th Oct. Do you want to leave at 8:44 (arriving 14:00) or 10:44 (arriving 16:00), or 12:44 (cheapest, though we don't care).

Is that 8.44 from Eindhoven or Brussels? If Eindhoven lets take early one.

> Really tempted to book first class. It's not much more. I bet there are rules saying we can't, though :)

Can you try? Worst thing that can happen is that they tell us off.

**Comment by Mark-Torrance** [comment]
Worst things that can happen are (a) we make Evgeny unhappy or (b) I have to pay. I'll ask, though.

**Comment by Mark-Torrance** [comment]
Good. Those trains are good for me. Can you identify trains from Nottingham that will meet those (actually probably better to go with an Open Return in case of delays) and I'll get these all booked.

**Comment by jensroes** [comment]
- Train Nottingham to London at 9.12am (no changes) on Oct 21
- Return (open is fine by me) 3.35pm to Nottingham (no changes).

**Comment by jensroes** [comment]
I think number 3. 3 has breakfast as well btw. I don't think the first one looks much better and is probably haunted. 

Don't worry too much about the practice studio. It would be nice to have a few days where I can play for a couple of hours but I'll be okay if not.

**Comment by Mark-Torrance** [comment]
Final check before booking. Do these times look ok?


3 | London   St Pancras Intl | 21   Oct 24 at    13:01 | Eindhoven | 21   Oct 24 at    19:16 | Second | £217.40
-- | -- | -- | -- | -- | -- | --
4 | Birmingham   New Street | 21   Oct 24 at    10:17 | Birmingham   New Street | 24   Oct 24 at    15:48 | Standard | £73.00
5 | Nottingham | 21   Oct 24 at    10:12 | Nottingham | 24   Oct 24 at    16:09 | Standard | £132.30
6 | Eindhoven | 24   Oct 24 at    08:14 | Rotterdam   Centraal | 24   Oct 24 at    09:16 | Second | £55.83
7 | Rotterdam   Centraal | 24   Oct 24 at    10:58 | London   St Pancras Intl | 24   Oct 24 at    13:37 | Second | £173.75

And staying at the Social Hub, with breakfast.

**Comment by RConijn** [comment]
Sidenote: not sure if I read this table correctly, but these prices are insane, should be half the price at least for the london-ehv part (~220 pounds return ticket). Did you try nsinternational / deutsche bahn? (although it doesn't matter much for the budget)

**Comment by Mark-Torrance** [comment]
I've not picked cheap times, but still these always come back from our travel agent at more than I expect. 

If you want something really insane, look at the prices of the UK tickets - Nottingham to London is an off-peak ticket - so cheaper. If Jens was travelling before 9:30 am the ticket price was £215 for a journey that lasts 1 hour and 45 mins.

**Comment by jensroes** [comment]
When I look at trains the prices for the 9.12 train from nottingham and the 10.12 train are about the same.

**Comment by Mark-Torrance** [comment]
The prices above are for the journeys we are sharing are for two people, not one. Thanks for checking Rianne - it said one person on the quote. Jens, those fare are pretty much the same as trainline, with a small booking fee.

@jensroes can I go ahead and book.

**Comment by jensroes** [comment]
I'd prefer the 9.12 train but if the price difference is so massive, 10.12 will be fine. That just means I shouldn't faff about.

**Comment by Mark-Torrance** [comment]
The tickets are off peak, not advance. So they are not booked onto a specific train. If 9:12 is off peak, then your ticket will work. Very worst case, just pay the difference on the train and claim back. The Open prices was about £100 more.

**Comment by jensroes** [comment]
One of things I have not understood about trains in this country. how do I know if 9.12 is off peak?

**Comment by Mark-Torrance** [comment]
These is a whole genetic memory thing that permits interpretation of UK rail fares. You don't stand a chance.

Normally 9:30. That 9:12 is still peak time (I've checked). The cheaper price is an Advance fare.

I could just not book you UK travel, and you claim back? I've done that lots of times. Or get the later train.

**Comment by jensroes** [comment]
Good so it's not me. That's good enough.
I think I'll just chance the 10.12 train.

**Comment by Mark-Torrance** [comment]
I've got onto a Eurostar arriving at the station 12 mins before departure. Not recommended, but the 1 hour in advance thing is flexible :)

Booking now.

**Comment by jensroes** [comment]
haha that would be great. That's what I used to do in Potsdam and even at NTU for some time.

**Comment by RConijn** [comment]
Multi-purpose those rooms - I've used them as nap room during my pregnancy as well (they have a much better couch than the dedicated nap room our university offers)
