### ISSUE TITLE
CRediT Taxonomy

### ISSUE THREAD

**Issue by jensroes** [jensroes/prowrite-mixture-models#13]
Apparently this needs to appear in the manuscript as well, although I've put this in the submission forum too. @RConijn and @Mark-Torrance, please check and edit.

Conceptualization: Jens, Mark, Rianne
Data curation: Jens, Mark
Formal analysis: Jens, Mark
Funding acquisition: Evgeny, Jens, Mark
Investigation: All
Methodology: Jens, Mark
Project administration: Jens, Evgeny
Resources: Gunn, Evgeny, Mark
Software: Evgeny, Jens
Supervision: Evgeny, Mark
Validation: don't know :)
(it means "Verification, whether as a part of the activity or separate, of the overall replication/reproducibility of results/experiments and other research outputs"
Visualization: Jens, Mark
Writing – original draft: Jens, Mark, Rianne
Writing – review & editing: Jens, Mark, RIanne

If you need details what these mean (I do) please see here: https://groups.niso.org/higherlogic/ws/public/download/31067/CRediT_Taxonomy_Terms_and_Definitions_list

**Comment by RConijn** [comment]
You don't need to include _all_ roles. So I usually only report the ones that I understand. You can easily leave out validation (and others if you want). Investigation might be a bit less relevant here as well, since we're working with second hand data.

**Comment by jensroes** [comment]
I've included these in the manuscript now. I've finally worked out how to change this sort of thing in `papaja` (as well as changing the author note). 

Please let me know if anything needs changing. @Mark-Torrance can you check if I've added Evgeny to the right bits?

**Comment by Mark-Torrance** [comment]
This looks good to me. I would remove the "supervision" heading altogether. I'd also remove "validation".
