### ISSUE TITLE
SIG writing abstract

### ISSUE THREAD

**Issue by jensroes** [jensroes/prowrite-mixture-models#6]
I'd like to present this at SIG writing with your names on it. Here is the abstract:

https://docs.google.com/document/d/1ytt4_bxZXdE99jTNNdHI6rjULH44QIdmKJfwrQqrt54/edit?usp=sharing

Feel free to make changes and add comments :)

**Comment by Mark-Torrance** [comment]
Made some suggested edits.

**Comment by jensroes** [comment]
@chukharev could you have a look too? Don't worry if not, Mark and Rianne seem already reasonably happy with it.
